services:
  backend:
    build:
      context: api/
      dockerfile: backend.Dockerfile
    ports:
      - "443:10000"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
  frontend:
    build:
      context: web/
      dockerfile: frontend.Dockerfile
    ports:
      - "80:80"
