name: build-frontend

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'web/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install
      working-directory: web/deer-react-app
    - run: npm ci
      working-directory: web/deer-react-app
    - run: npm run build --if-present
      working-directory: web/deer-react-app
    - run: npm test
      working-directory: web/deer-react-app
