name: deploy-backend

on:
  workflow_dispatch:

env:
  BACKEND_IMAGE_NAME: dwd_backend

jobs:
  backend_push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build . --file backend.Dockerfile --tag $BACKEND_IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"
        working-directory: api/
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$BACKEND_IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "master" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $BACKEND_IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

  backend_deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    needs: backend_push
    environment: aws-prod
    steps:
      - name: SSH & Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_AWS_BACKEND_SERVER_IP }}
          username: ${{ secrets.SSH_SERVER_USER }}
          key: ${{ secrets.SSH_BACKEND_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_BACKEND_PASSPHRASE }}
          script: |
            docker rm -f $(docker ps -f 'name=dwd_backend' -q)
            docker rmi $(docker images 'ghcr.io/deerwomandezigns/dwd_backend' -q)
            branch="${{github.ref}}"
            docker pull ghcr.io/deerwomandezigns/dwd_backend:${branch##*/}
            image=$(docker images 'ghcr.io/deerwomandezigns/dwd_backend' -q)
            docker run --detach \
              --env "AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY_ID }}" \
              --env "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
              --env "AWS_DEFAULT_REGION=us-east-2" \
              --env "VIRTUAL_HOST=api.deerwoman-dezigns.com" \
              --env "LETSENCRYPT_HOST=api.deerwoman-dezigns.com" \
              --name dwd_backend \
              $image
