name: tf-plan

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.tf'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Verify Terraform version
        run: terraform --version
        working-directory: infra/aws

      - name: Terraform init
        run: terraform init -input=false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: infra/aws

      - name: Terraform validation
        run: terraform validate
        working-directory: infra/aws

      - name: Terraform plan
        run: terraform plan -input=false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: infra/aws
